services:
  postgres:
    image: postgres:16-alpine
    container_name: landing_postgres
    restart: always
    environment:
      POSTGRES_DB: landing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d landing_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hospital-network

  minio:
    image: minio/minio
    container_name: minio-landingPage
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - hospital-network

  redis:
    image: redis:7-alpine
    container_name: landing_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hospital-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  minio_data:
  redis_data:

networks:
  hospital-network:
    driver: bridge